Scanner login fix
ugent/Studieplekken pull request #49
Opened 2022-12-15 19:15 UTC by EwoutV

closes #27, closes #14 

New authorization logic (using custom guards per route) also fixes the issue where scanners had to log-in twice (happened because the asynchronous nature of authorizing users). There are also some ESLint fixes (mainly indentation) which should be ignored while reviewing. In the near future I will probably fix all these styling errors in one go so we don't have to deal with it in future PRs.

2022-12-18 19:58 UTC, smessie reviewed
This was a hell to review, maybe we shouldn't change the indentation after all... what do you think?

2022-12-18 19:58 UTC, smessie commented on frontend/src/app/app.module.ts
> +            guards: [['scanner'], ['admin']]
How does this system work? Why not having a "minimum rank" thing and allowing everyone with that rank and up?
I think everything a scanner can, an authority person of the same location should be able to do the same.

2022-12-18 19:58 UTC, smessie commented on frontend/src/app/scan/scanning-locations/scanning-locations.component.html
> -  <span>Hello</span>
Bye 😅

2022-12-18 19:58 UTC, smessie commented on frontend/src/app/services/authentication/login-redirect.service.ts
> +        const url = localStorage.getItem('afterLogin');
Is this fallback not needed anymore?

2022-12-18 19:58 UTC, smessie commented on frontend/src/app/services/guard/authorization/authorization-guard.service.ts
> +                // We only redirect if the current user isn't logged-in.
What do we do and/or want to do if the user is logged in?
When I try it myself I'm still being redirected to login page even though I'm a logged in authority person.

2022-12-18 19:59 UTC, smessie commented
Can you also rebase your branch so it is up-to-date with master again? :)

2022-12-19 09:47 UTC, EwoutV commented on frontend/src/app/app.module.ts
> +            guards: [['scanner'], ['admin']]
I chose the most flexible system where you can define custom combinations of roles, so when there are any roles added in the future it's very easy to implement them in the authorization system. I understand that for now, all roles extend each other from bottom-up (user -> scanner -> authority -> admin), so an implementation where all roles inherits from another would indeed have been easier. I am not sure though if this can change in the future? In that case, when a different role gets introduced, we'd have to re-write the authorization system yet again.

To provide you with an example on how it works: a guard list of `[['authority'], ['admin']]` means that the guard should only be available to a scanner or an admin. When you provide e.g. `[['scanner', 'role'], ['admin']]`, it means the route is only available when the current user is either a scanner AND has the other role, OR it is an admin.

A bit too overkill, perhaps? If you want I can use the system where each role inherits from each other, if you are sure this way of working of roles will not change in the near future :sweat_smile: This can be done in like 10 minutes...

2022-12-19 09:48 UTC, EwoutV commented on frontend/src/app/scan/scanning-locations/scanning-locations.component.html
> -  <span>Hello</span>
I have no chill.

2022-12-19 09:49 UTC, EwoutV commented on frontend/src/app/services/authentication/login-redirect.service.ts
> +        const url = localStorage.getItem('afterLogin');
I don't think so, I made sure the `afterLogin` is always set when navigating to and from the authentication process...

2022-12-19 09:50 UTC, EwoutV commented on frontend/src/app/app.module.ts
> +            guards: [['scanner'], ['admin']]
I am by the way also a fan of ditching this indentation nonsense, maybe we can do it in one go as a separate issue

2022-12-19 09:51 UTC, EwoutV commented on frontend/src/app/services/authentication/login-redirect.service.ts
> +        const url = localStorage.getItem('afterLogin');
I don't think so, I made sure the `afterLogin` is always set when navigating to and from the authentication process...

2022-12-19 09:53 UTC, EwoutV commented on frontend/src/app/services/guard/authorization/authorization-guard.service.ts
> +                // We only redirect if the current user isn't logged-in.
Probably show a access denied page of some sort? What are you trying to access as an authority?

2022-12-23 09:11 UTC, AurisAudentis requested changes
This is much nicer than it was, good job! 

One thing I want to add though: when running automated code editing tools such as linters, please make a separate PR first with **only** these automated changes. You can base your actually functional PR off of that one, which should create two really clean diffs.
The same thing counts for moving large blocks of code: if you want to move something then edit, do it in two PR's so the diffs show everything clearly.

2022-12-23 09:11 UTC, AurisAudentis commented on frontend/src/app/services/guard/authorization/authorization-guard.service.ts
> +                return of(authorized);
You can change this to a simple 'map' instead of a switchMap and remove the 'of' here, since there is no reason for this to be wrapped in an observable.

2022-12-23 09:11 UTC, AurisAudentis commented on frontend/src/app/services/guard/authorization/authorization-guard.service.ts
> +                        }
```suggestion
const currentAuthorized = authorization.every(guard => this.hasGuard(guard));
```
Is equivalent and much shorter I believe

2022-12-23 09:11 UTC, AurisAudentis commented on frontend/src/app/services/guard/authorization/authorization-guard.service.ts
> +                if (authorizations && authorizations.length) {
```suggestion
                const authorizations: string[][] = route.data.guards || [];
```
avoids entire if statement

2022-12-23 09:11 UTC, AurisAudentis commented on frontend/src/app/services/authentication/login-redirect.service.ts
> +        const url = localStorage.getItem('afterLogin');
Where do you redirect after initial login? e.g. when coming from the portal, or even directly to login?

2022-12-25 11:24 UTC, EwoutV commented on frontend/src/app/services/authentication/login-redirect.service.ts
> +        const url = localStorage.getItem('afterLogin');
When the `afterLogin` key is not set, Angular redirects to / automatically (when calling `navigateByUrl(null)`). I think this is desired behavior?

2022-12-25 11:25 UTC, EwoutV commented on frontend/src/app/services/guard/authorization/authorization-guard.service.ts
> +                        }
True, fixed!

2022-12-26 11:57 UTC, AurisAudentis commented on frontend/src/app/services/authentication/login-redirect.service.ts
> +        const url = localStorage.getItem('afterLogin');
SGTM

2022-12-26 11:59 UTC, AurisAudentis approved these changes
Requested changes look good to me, please wait for approval from @smessie though since he is the authority.

2022-12-26 22:24 UTC, smessie commented
Git says brrr, closed in favor of #56

2022-12-26 22:24 UTC, closed without merging